export const AVAILABLE_SONGS = [
	{
		file: '1-salpriadi.mp3',
		name: 'Mesra-mesraannya kecil-kecilan dulu',
		artist: 'Sal Priadi',
		color: '#393939',
		image: '1-salpriadi.png',
	},
	{
		file: '2-hindia.mp3',
		name: 'everything u are',
		artist: 'Hindia',
		color: '#393939',
		image: '2-hindia.png',
	},
	{
		file: '15-bruno.mp3',
		name: 'Risk It All',
		artist: 'Bruno Mars',
		color: '#393939',
		image: '15-bruno.png',
	},
	{
		file: '3-yahya.mp3',
		name: 'keepyousafe',
		artist: 'Yahya',
		color: '#393939',
		image: '3-yahya.png',
	},
	{
		file: '13-mora.mp3',
		name: 'REINA',
		artist: 'Mora, Saiko',
		color: '#393939',
		image: '13-mora.png',
	},
	{
		file: '14-jahmiel.mp3',
		name: 'U Me Luv',
		artist: 'Jahmiel',
		color: '#393939',
		image: '14-jahmiel.png',
	},
	{
		file: '4-ardhito.mp3',
		name: 'Waking Up Together With You',
		artist: 'Ardhito Pramono',
		color: '#393939',
		image: '4-ardhito.png',
	},
	{
		file: '6-paul.mp3',
		name: "THANK YOU 4 LOVIN' ME",
		artist: 'Paul Partohap',
		color: '#393939',
		image: '6-paul.png',
	},
	{
		file: '8-zack.mp3',
		name: 'Give Me Your Forever',
		artist: 'Zack Tabudlo',
		color: '#393939',
		image: '8-zack.png',
	},
	{
		file: '9-lady.mp3',
		name: 'Shallow',
		artist: 'Lady Gaga, Bradley Cooper',
		color: '#393939',
		image: '9-lady.png',
	},
	{
		file: '11-nadhif.mp3',
		name: 'bergema sampai selamanya',
		artist: 'Nadhif Basalamah',
		color: '#393939',
		image: '11-nadhif.png',
	},
	{
		file: '12-sal.mp3',
		name: "I'd like to watch you sleeping",
		artist: 'Sal Priadi',
		color: '#393939',
		image: '12-sal.png',
	},
] as const;
