export const AVAILABLE_SONGS = [
	{
		file: '1-salpriadi.mp3',
		name: 'Mesra-mesraannya kecil-kecilan dulu',
		artist: 'Sal Priadi',
		color: '#393939',
		image: '1-salpriadi.png',
	},
	{
		file: '2-hindia.mp3',
		name: 'everything u are',
		artist: 'Hindia',
		color: '#E91E63',
		image: '2-hindia.png',
	},
	{
		file: '3-yahya.mp3',
		name: 'keepyousafe',
		artist: 'Yahya',
		color: '#9c27b0',
		image: '3-yahya.png',
	},
	{
		file: '4-ardhito.mp3',
		name: 'Waking Up Together With You',
		artist: 'Ardhito Pramono',
		color: '#795548',
		image: '4-ardhito.png',
	},
	{
		file: '6-paul.mp3',
		name: "THANK YOU 4 LOVIN' ME",
		artist: 'Paul Partohap',
		color: '#FF5722',
		image: '6-paul.png',
	},
	{
		file: '7-elle.mp3',
		name: 'You',
		artist: 'Elle Eliades, R.L. KING',
		color: '#0073ce',
		image: '7-elle.png',
	},
	{
		file: '8-zack.mp3',
		name: 'Give Me Your Forever',
		artist: 'Zack Tabudlo',
		color: '#9E9E9E',
		image: '8-zack.png',
	},
	{
		file: '9-lady.mp3',
		name: 'Shallow',
		artist: 'Lady Gaga, Bradley Cooper',
		color: '#FFD700',
		image: '9-lady.png',
	},
	{
		file: '11-nadhif.mp3',
		name: 'bergema sampai selamanya',
		artist: 'Nadhif Basalamah',
		color: '#783',
		image: '11-nadhif.png',
	},
	{
		file: '12-sal.mp3',
		name: "I'd like to watch you sleeping",
		artist: 'Sal Priadi',
		color: '#f90',
		image: '12-sal.png',
	},
] as const;
